### ISSUE TITLE
和 YYModel 相比优势在哪儿？

### ISSUE THREAD

**Issue by skyline75489** [netyouli/WHC_Model#2]
主体代码跟 YYModel 是类似的

**Comment by netyouli** [comment]
优势在更强大使用更简单方便直接，在不使用别名情况下不区分属性明大小写，数组或者字典不需要指定类型，核心与WHC_DataModelfactory
自动把json转换为类mac工具完全兼容

**Comment by skyline75489** [comment]
不区分名称大小写，以及数组或者字典不需要指定类型，我个人感觉只是算是特性，而且还是那种相对 implicit 的特性，可能会导致使用错误，是不是好的特性还有待商榷。

另外，YYModel 虽然是使用 MIT 协议开源，出于对原作者的尊重，至少也应该附上原项目的链接。 YYModel deserves to be mentioned.

**Comment by LawrenceHan** [comment]
@skyline75489 类似的问题我在国外的开源库上也见过，那个库的原作者说既然是在MIT License下，那么代表允许这么做。YYModel和该库都是在MIT License许可下的，所以他这么做并没有违反原作者的意图。

## But YYModel deserves to be mentioned

**Comment by MichaelHuyp** [comment]
@netyouli 数组解析情况下 不指定类型 是在返回json的Key与定义的模型名一致情况下,或者要实现replacePropertyNameMap这个方法替换.. 可以不可以直接获取到定义字段的类型呢
例如@property (nonatomic , strong) NSArray<PolicyRuleList *>     * PolicyRuleList;
根据NSArray<PolicyRuleList *> 就能获取到<>尖括号里面的模型类型名...
