### ISSUE TITLE
同属性名不同类型解析问题

### ISSUE THREAD

**Issue by c-ys** [netyouli/WHC_Model#3]
使用过程中出现一个问题，模型里的某个属性不同情况下会有不同的类型，比如我使用过程中有一个属性expressInfo是存储快递信息，自定义了类ExpressInfo,

//数组或字典替换存储类
+ (NSDictionary <NSString *, Class> *)whc_ModelReplaceContainerElementClassMapper {
    return @{@"expressInfo" : NSClassFromString(@"ExpressInfo")};
}

但是有时候订单是没有快递信息的，后台的这个key会传回flase,是bool类型，而解析过程中，如果第一次解析没有快递信息后，其他的数据即使是有快递信息，解析的结果也会是nil。

**Comment by c-ys** [comment]
不好意思，上方的方法复制错了,使用的是这个方法
/// 模型类可自定义属性类型<替换实际属性名,实际类>
+ (NSDictionary <NSString *, Class> *)whc_ModelReplacePropertyClassMapper{
    return @{@"expressInfo" : NSClassFromString(@"ExpressInfo")};
}

**Comment by netyouli** [comment]
首先json的key对应的数据类型肯定是要唯一确定的，否则只能手动判断了
如果属性名为expressInfo 对应的模型类为ExpressInfo这不需要重新映射，WHC_Model会自动匹配不区分属性名称大小写

**Comment by DolphinsLoveCats** [comment]
/// 模型类可自定义属性名称<json key名, 替换实际属性名>
+ (NSDictionary <NSString *, NSString *> *)whc_ModelReplacePropertyMapper;
/// 模型数组/字典元素对象可自定义类<替换实际属性名,实际类>
+ (NSDictionary <NSString *, Class> *)whc_ModelReplaceContainerElementClassMapper;
/// 模型类可自定义属性类型<替换实际属性名,实际类>
+ (NSDictionary <NSString *, Class> *)whc_ModelReplacePropertyClassMapper;

关于这3个方法第一个在demo中发现没有应用
第一个  可以看懂什么意思
但是 第二个 和第三个 不是很理解

比如  json数据 返回 格式如下

 {       "outqty1" : 2.5,
          "line" : 13051,
          "copy" : [
            {
              "pmodel" : "108.0G",
              "copy" : "拷贝字符串",
              "pprate" : 40,
           },
          {
              "pmodel" : "101.0G",
              "copy" : "拷贝字符串1",
              "pprate" : 41,
          }
                      ]
}

不知道该如何定义这个 数组的copy类型
