### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by qimuya3** [netyouli/WHC_Model#4]
当服务器返回的json的属性值为null时，但是对象的属性为NSInteger时，解释出错，程序crash；
例如:服务返回：obj:null;   而oc的对象的属性@property(nonatomic, assign) NSInteger obj;

错误提示的大意为：无法将NSNull转换到NSInteger；

**Comment by netyouli** [comment]
关于NSInteger类型可能为null的情况你可以把数值类型声明为NSNumber对象即可，后期也会做兼容处理，但是可能会牺牲一点性能

**Comment by qimuya3** [comment]
你好，感谢你的回复。建议做兼容处理，毕竟在oc里，用NSInteger是很多的。如果改成NSNumber,对于整个工程的修改量太大。

**Comment by netyouli** [comment]
恩，下个版本会，你也可以叫你们服务端处理一下，你们接口返回数据不规范

**Comment by qimuya3** [comment]
好的，谢谢。
